package com.example.gocampingcompany.star.model

data class StarItem(
    val title : String,
    val addr1 : String,
    val addr2 : String,
    val tel : String,
    val image : String,
    val doName : String,
    val siName : String,
    val contentId : String,
    val lat : String,
    val lon : String,
    val lineIntro : String,
    val lctCl : String,
    val facltDivNm : String,
    val induty : String,
    val operPdCl : String,
    val operDeCl : String,
    val homepage : String,
    val intro : String,
    val sbrsCl : String,
    val gnrlSiteCo : String,
    val glampSiteCo : String,
    val glampInnerFclty : String,
    val brazierCl : String,
    val extshrCo : String,
    val frprvtWrppCo : String,
    val frprvtSandCo : String,
    val fireSensorCo : String,
    val animalCmgCl : String,
    val siteBottomCl1 : String,
    val siteBottomCl2 : String,
    val siteBottomCl3 : String,
    val siteBottomCl4 : String,
    val siteBottomCl5 : String,

)
